In [1]:
import duckdb

In [2]:
with duckdb.connect("world_bank.db") as con:
    df = con.table("electricity").to_df()
    print(df)

     Country Name Country Code  Time Time Code  Percent of Pop
0     Afghanistan          AFG  1990    YR1990        0.010000
1     Afghanistan          AFG  1991    YR1991        0.010000
2     Afghanistan          AFG  1992    YR1992        0.010000
3     Afghanistan          AFG  1993    YR1993        0.010000
4     Afghanistan          AFG  1994    YR1994        0.010000
...           ...          ...   ...       ...             ...
6988     Zimbabwe          ZWE  2012    YR2012       36.728878
6989     Zimbabwe          ZWE  2013    YR2013       37.076813
6990     Zimbabwe          ZWE  2014    YR2014       32.300000
6991     Zimbabwe          ZWE  2015    YR2015       33.700000
6992     Zimbabwe          ZWE  2016    YR2016       38.145138

[6993 rows x 5 columns]

In [3]:
df.head()

  Country Name Country Code  Time Time Code  Percent of Pop
0  Afghanistan          AFG  1990    YR1990            0.01
1  Afghanistan          AFG  1991    YR1991            0.01
2  Afghanistan          AFG  1992    YR1992            0.01
3  Afghanistan          AFG  1993    YR1993            0.01
4  Afghanistan          AFG  1994    YR1994            0.01

In [4]:
# create a connection to the world_bank.db
con = duckdb.connect("world_bank.db")

# show all tables in the database
print(con.execute("SHOW TABLES").fetchall())

[('electricity',)]

In [5]:
# create a connection to the world_bank.db
con2 = duckdb.connect("world_bank.db")

# show all tables in the database
print(con2.execute("SHOW TABLES").fetchall())

[('electricity',)]

In [6]:
con.table("electricity").show()

┌──────────────┬──────────────┬───────┬───────────┬─────────────────────┐
│ Country Name │ Country Code │ Time  │ Time Code │   Percent of Pop    │
│   varchar    │   varchar    │ int64 │  varchar  │       double        │
├──────────────┼──────────────┼───────┼───────────┼─────────────────────┤
│ Afghanistan  │ AFG          │  1990 │ YR1990    │ 0.00999999977648258 │
│ Afghanistan  │ AFG          │  1991 │ YR1991    │ 0.00999999977648258 │
│ Afghanistan  │ AFG          │  1992 │ YR1992    │ 0.00999999977648258 │
│ Afghanistan  │ AFG          │  1993 │ YR1993    │ 0.00999999977648258 │
│ Afghanistan  │ AFG          │  1994 │ YR1994    │ 0.00999999977648258 │
│ Afghanistan  │ AFG          │  1995 │ YR1995    │ 0.00999999977648258 │
│ Afghanistan  │ AFG          │  1996 │ YR1996    │ 0.00999999977648258 │
│ Afghanistan  │ AFG          │  1997 │ YR1997    │ 0.00999999977648258 │
│ Afghanistan  │ AFG          │  1998 │ YR1998    │  0.0219771377742291 │
│ Afghanistan  │ AFG          │  1999 │ YR1999    │   0.179634585976601 │
│    ·         │  ·           │    ·  │   ·       │            ·        │
│    ·         │  ·           │    ·  │   ·       │            ·        │
│    ·         │  ·           │    ·  │   ·       │            ·        │
│ Zimbabwe     │ ZWE          │  2007 │ YR2007    │    35.1844787597656 │
│ Zimbabwe     │ ZWE          │  2008 │ YR2008    │    35.4573097229004 │
│ Zimbabwe     │ ZWE          │  2009 │ YR2009    │    43.3690818728747 │
│ Zimbabwe     │ ZWE          │  2010 │ YR2010    │    36.0630569458008 │
│ Zimbabwe     │ ZWE          │  2011 │ YR2011    │                36.9 │
│ Zimbabwe     │ ZWE          │  2012 │ YR2012    │    36.7288780212402 │
│ Zimbabwe     │ ZWE          │  2013 │ YR2013    │    37.0768127441406 │
│ Zimbabwe     │ ZWE          │  2014 │ YR2014    │                32.3 │
│ Zimbabwe     │ ZWE          │  2015 │ YR2015    │                33.7 │
│ Zimbabwe     │ ZWE          │  2016 │ YR2016    │    38.1451377868652 │
└──────────────┴──────────────┴───────┴───────────┴─────────────────────┘
  6993 rows (20 shown)                                        5 columns

In [7]:
# to pandas
df = con.table("electricity").to_df()
df.head()

  Country Name Country Code  Time Time Code  Percent of Pop
0  Afghanistan          AFG  1990    YR1990            0.01
1  Afghanistan          AFG  1991    YR1991            0.01
2  Afghanistan          AFG  1992    YR1992            0.01
3  Afghanistan          AFG  1993    YR1993            0.01
4  Afghanistan          AFG  1994    YR1994            0.01

In [8]:
con.close()